safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
permalink: /:categories/:title.html
url: http://falcao.it/jekyll-playground
keywords: Lettuce, BDD, Python, Cucumber, Django, Sure
pygments: true
future: true
exclude: [Makefile]
markdown: redcarpet2
